config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: {
        sessions: 'users/sessions'
    }
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get 'up' => 'rails/health#show', as: :rails_health_check

    # Defines the root path route ("/")
    # root "posts#index"
    root 'home#index'

    get 'home/index'

    resources :exercises
    resources :workouts
    resources :trainings
    resources :rep_sets
    resources :templates
end

app/models/workout.rb
class Workout < ApplicationRecord
    belongs_to :user

    has_many :trainings
    has_many :rep_sets

    alias_attribute :start_time, :created_at

    before_save do |workout|
        if workout.template_id
            template_name = Template.find(template_id).name
            workout.name = "#{template_name} Workout"
        else
            workout.name = "#{determine_workout_name} Workout"
        end
    end

    private

    def determine_workout_name
        hour = Time.zone.now.localtime.hour

        if hour.between?(0, 4) || hour.between?(21, 24)
            'Night'
        elsif hour.between?(5, 11)
            'Morning'
        elsif hour.between?(12, 16)
            'Afternoon'
        elsif hour.between?(17, 20)
            'Evening'
        end
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_workout, only: [:show, :edit]

    def index
        start_date = params.fetch(:start_date, Time.zone.today).to_date
        @workouts = Workout.where(created_at: (start_date.beginning_of_day)..((start_date + 2).end_of_day))
    end

    def show
        @trainings = Training.where(workout_id: @workout).all
        @templates = current_user.templates.all
        @previous_template_workout = Workout.where(created_at: ...@workout.created_at).last
    end

    def new
        @workout = current_user.workouts.build
    end

    def edit
        @workout_trainings = @workout.trainings.order(id: :asc)
    end

    def create
        if params[:template_id]
            @workout = current_user.workouts.build(user_id: current_user.id, template_id: params[:template_id])
            exercises = current_user.templates.find(params[:template_id]).exercise_ids
        else
            @workout = current_user.workouts.build(user_id: current_user.id)
            exercises = workout_params[:exercises]
        end

        if @workout.save
            create_trainings(exercises)
            redirect_to edit_workout_path(@workout)
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update; end

  private

    def workout_params
        params.require(:workout).permit(exercises: [])
    end

    def set_workout
        @workout = current_user.workouts.find(params[:id])
    end

    def create_trainings(exercise_ids)
        exercise_ids.each do |exercise|
            @training = Training.create(workout_id: @workout.id, exercise_id: exercise)
            if @training.save
                RepSet.create(workout_id: @workout.id, exercise_id: exercise, training_id: @training.id, reps: nil,
                              weight: nil)
            else
                render :new, status: :unprocessable_entity
            end
        end
    end

end

app/views/workouts/_rep_set_list.html.erb
<%= turbo_frame_tag "rep_set_list" do %>
  <% workout_trainings.each do |training| %>
    <div class="shrink">
      <ul class="w-full flex flex-col shrink gap-4">
        <li class="w-full flex flex-col shrink gap-4">
          <h3 class="text-lg -mb-4 text-secondary"><%= current_user.exercises.find_by(id: training.exercise_id).name %></h3>
          <% workout.rep_sets.where(training_id: training.id).order(:id).each do |rep_set| %>
            <%= form_with model: rep_set, class: "w-full mt-4" do |form| %>
              <div class="w-full flex flex-row gap-2">
                <%= form.text_field :reps, placeholder: "Reps", class: "shrink w-1/6 input input-bordered input-primary w-full max-w-xs bg-transparent text-white min-w-0" %>
                <%= form.text_field :weight, placeholder: "Weight", class: "shrink min-w-0 input input-bordered input-primary w-full max-w-xs bg-transparent text-white " %>
                <%= hidden_field_tag 'workout_id', @workout.id %>
                <%= hidden_field_tag 'training_id', training.id %>
                <%= button_tag :submit, method: :put, class: 'basis-1/6 btn btn-square btn-outline btn-secondary hover:btn-success', title: "Save Set" do %>
                  <%= icon('fa-solid', 'check') %>
                <% end %>
                <%= link_to rep_set_path(rep_set, rep_set: { workout_id: @workout.id, training_id: training.id} ), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, title: "Delete Exercise" do %>
                  <div class="basis-1/6 btn btn-square btn-outline btn-secondary hover:btn-error">
                    <%= icon('fa-solid', 'x')%>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </li>
        <%= button_to rep_sets_path, params: { rep_set: { :workout_id => @workout.id, :training_id => training.id, :exercise_id => training.exercise_id } }, method: :post, form: { data: { } }, title: "Add a new Set" do %>
          <div class="w-full btn btn-sm btn-outline btn-secondary hover:btn-error">
            Add Set
          </div>
        <% end %>
      </ul>

      <div class="divider divider-vertical divider-neutral mt-2"></div>
    </div>
  <% end %>
<% end %>

app/views/workouts/_template_workout_view.html.erb
<div class="mt-7">
  <h2 class="text-xl font-bold text-primary">Weight Pushed</h2>
  <div class="mt-2">
    <%= column_chart [['Previous Workout', @previous_template_workout.rep_sets.sum(:reps) * @previous_template_workout.rep_sets.sum(:weight)],['This Workout', @workout.rep_sets.sum(:reps) * @workout.rep_sets.sum(:weight)]], ytitle: 'Pounds' %>
  </div>

  <ul class="mt-4 flex flex-col gap-y-4">
    <% @trainings.each do |training| %>
      <div class="mt-4 mb-6">
        <h4 class="text-lg font-bold text-secondary"><%= current_user.exercises.find(training.exercise_id).name %></h4>
        <li class="grid grid-cols-3 gap-10 border-b border-secondary mt-2 pb-1">
          <div>
            Set #
          </div>
          <div>
            Reps
          </div>
          <div>
            Weight
          </div>
        </li>
        <% i = 1 %>
        <% @workout.rep_sets.where(training_id: training.id).order(:id).each do |set| %>
          <li class="grid grid-cols-3 gap-10 mt-2">
            <div> <%= i %> </div>
            <div>
              <%= set.reps %>
            </div>
            <div>
              <%= set.weight %>
            </div>
          </li>
          <% i += 1 %>
        <% end %>
      </div>
    <% end %>
  </ul>
</div>

app/views/workouts/_workout_list.html.erb
<% workouts.reverse_each do |workout| %>
  <div class="card bg-base-content shadow-xl flex-1 hover:bg-neutral-content">
    <%= link_to workout_path(workout.id) do %>
      <div class="card-body w-full">
        <h2 class="card-title text-primary-content"><%= workout.name %></h2>
        <p class="text-secondary-content text-xs -mt-2"><%= workout.created_at.strftime('%B %d, %Y') %></p>
        <p class="text-secondary-content text-xs truncate w-4/12 -mt-2"><%= format_exercise_names(workout, nil) %><p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/workouts/_workout_view.html.erb
<div class="mt-7">
  <ul class="flex flex-col gap-y-4">
    <% @trainings.each do |training| %>
      <div class="mt-4 mb-6">
        <h4 class="text-lg font-bold text-secondary"><%= current_user.exercises.find(training.exercise_id).name %></h4>
        <li class="grid grid-cols-3 gap-10 border-b border-secondary mt-2 pb-1">
          <div>
            Set #
          </div>
          <div>
            Reps
          </div>
          <div>
            Weight
          </div>
        </li>
        <% i = 1 %>
        <% @workout.rep_sets.where(training_id: training.id).order(:id).each do |set| %>
          <li class="grid grid-cols-3 gap-10 mt-2">
            <div> <%= i %> </div>
            <div>
              <%= set.reps %>
            </div>
            <div>
              <%= set.weight %>
            </div>
          </li>
          <% i += 1 %>
        <% end %>
      </div>
    <% end %>
  </ul>
</div>

app/views/workouts/edit.html.erb
<div class="w-11/12 max-w-11/12 mt-10 mx-auto flex flex-col">

  <div class="flex flex-row justify-between items-center">
    <h1 class="text-3xl font-bold shrink text-primary">Edit Your <%= @workout.name %></h1>

    <%= link_to workout_path(@workout) do %>
      <div class="btn btn-primary mt-3">
        Back to workout page
      </div>
    <% end %>
  </div>


  <div class="w-full max-w-full flex flex-col mt-5 mb-14">
    <%= render "workouts/rep_set_list", workout: @workout, workout_trainings: @workout_trainings %>
  </div>
</div>

app/views/workouts/index.html.erb
<div class="w-11/12 mt-10 mx-auto flex flex-col">
  <div class="flex flex-row justify-between items-center">
    <h2 class="text-3xl font-bold shrink text-primary">Your Workouts</h2>
    <a href=<%= new_workout_path %>>
         <button type="button" class="btn btn-primary ml-3">New Workout</button>
    </a>
  </div>

  <div class="mt-7">
    <%= calendar(number_of_days: 3, events: @workouts) do |date, events| %>
      <div class="flex flex-col justify-center items-center self-center">
        <div class="shrink text-nowrap self-center mt-2">
          <%= date %>
        </div>
        <div>
          <% events.each do |event| %>
            <div class="badge badge-primary badge-xs mt-2"></div>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="mt-14 w-full">
    <h2 class="text-2xl font-bold text-secondary">Weeks Workouts</h2>
      <% if @workouts.length < 1 %>
        <p class="mt-4">No workouts for this week</p>
      <% else %>
        <div class="flex flex-col flex-wrap gap-3 mt-4">
          <%= render "workouts/workout_list", workouts: @workouts %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/workouts/new.html.erb
<div class="w-11/12 pt-10 mx-auto flex flex-col">
  <h1 class="text-3xl font-bold">Create a Workout</h1>
  <div class="workout_start mt-7 flex flex-col">
    <h3 class="text-lg">Start by selecting exercises</h3>
    <p class="text-xs">
    (Don't worry you can add/remove exercises after as well)
    </p>
    <div class="mt-5">
      <% if current_user.exercises.empty? %>
        <p>It looks like you don't have any exercises created, click <%= link_to "here", exercises_path, class: "text-red-300 hover:underline" %> to create some!</p>
      <% else %>
        <%= form_with model: @workout do |form| %>

          <ul class="flex flex-col mt-10">
            <% current_user.exercises.each do |exercise| %>
              <div class="flex flex-row justify-between">
                <li class="flex flex-col justify-between">
                  <%= exercise.name %>
                </li>
                <%= check_box_tag 'workout[exercises][]', exercise.id, class: "toggle" %>
              </div>
              <div class="divider divider-neutral"></div>
            <% end %>
          </ul>

            <%= form.submit class: 'btn btn-primary' %>

        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/workouts/show.html.erb
<div class="w-11/12 mt-10 mx-auto flex flex-col">

  <div class="flex flex-row justify-between items-center">
    <h2 class="text-3xl font-bold shrink text-primary"><%= @workout.name %></h2>

    <%= link_to edit_workout_path(@workout) do %>
      <div class="btn btn-primary mt-3">
        Edit this workout
      </div>
    <% end %>
  </div>

  <span class="mt-4"><%= local_time(@workout.created_at) %></span>

    <% if @workout.template_id.present? %>
      <%= render "workouts/template_workout_view", workout: @workout, trainings: @trainings %>
    <% else %>
      <%= render "workouts/workout_view", workout: @workout, trainings: @trainings %>
    <% end %>
</div>