config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: {
        sessions: 'users/sessions'
    }
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get 'up' => 'rails/health#show', as: :rails_health_check

    # Defines the root path route ("/")
    # root "posts#index"
    root 'home#index'

    get 'home/index'

    resources :exercises
    resources :workouts
    resources :trainings
    resources :rep_sets
    resources :templates
end

app/views/templates/_template_form.html.erb
<div class="mt-5">
  <% if current_user.exercises.empty? %>
    <p>It looks like you don't have any exercises created, click <%= link_to "here", exercises_path, class: "text-red-300 hover:underline" %> to create some!</p>
  <% else %>
    <%= form_with model: template do |form| %>

      <%= form.text_field :name, placeholder: 'Template Name', class: "input input-bordered input-primary w-full max-w-xs bg-transparent text-white" %>

      <h3 class="text-xl mt-10">Select this Templates exercise's</h3>
      <ul class="flex flex-col mt-4">
        <% current_user.exercises.each do |exercise| %>
          <div class="flex flex-row justify-between">
            <li class="flex flex-col justify-between">
              <%= exercise.name %>
            </li>
            <%= check_box_tag 'template[exercise_ids][]', exercise.id, template.exercise_ids.include?(exercise.id), class: "toggle" %>
          </div>
          <div class="divider divider-neutral"></div>
        <% end %>
      </ul>

      <%= form.submit class: 'btn btn-primary' %>

    <% end %>
  <% end %>
</div>

app/views/templates/_template_list.html.erb
<%= turbo_frame_tag "exercise_list" do %>
  <div class="flex flex-col w-full gap-3 mt-4">
  <ul>
    <% templates.each do |template| %>
      <div class="flex flex-row justify-between max-w-full">
        <div class="flex flex-col ">
          <li>
            <%= template.name %>
          </li>
          <li class="flex-none grow-0 text-xs truncate max-w-64">
            <%= @template_exercises[template.id] %>
          </li>
        </div>
        <div class="flex flex-row">
          <%= link_to edit_template_path(template), class: "btn btn-square btn-outline btn-secondary mr-4 hover:btn-success", data: { turbo: false } do %>
            <%= icon('fa-solid', 'pen-to-square')%>
          <% end %>
          <%= button_to workouts_path(template_id: template.id), method: "post", class: "btn btn-square btn-outline btn-secondary hover:btn-info", data: { turbo: false } do %>
            <%= icon('fa-solid', 'plus')%>
          <% end %>
        </div>
      </div>
      <div class="divider divider-neutral"></div>
    <% end %>
  </ul>
  </div>
<% end %>

app/views/templates/edit.html.erb
<div class="w-11/12 pt-10 mx-auto flex flex-col">
  <h1 class="text-3xl font-bold">Edit your Workout Template</h1>
  <div class="mt-7 flex flex-col">

    <%= render "templates/template_form", template: @template %>

  </div>
</div>

app/views/templates/index.html.erb
<div class="w-11/12 mt-10 mx-auto flex flex-col">
  <div class="flex flex-row justify-between items-center">
    <h2 class="text-3xl font-bold shrink text-primary">Your Templates</h2>
    <a href=<%= new_template_path %>>
      <button type="button" class="btn btn-primary ml-3">New Template</button>
    </a>
  </div>

    <div class="mt-14 w-full">
      <% if @templates.length < 1 %>
        <p class="mt-4">You have no Templates created.</p>
      <% else %>
        <%= render "templates/template_list", templates: @templates %>
      <% end %>
    </div>
</div>

app/views/templates/new.html.erb
<div class="w-11/12 pt-10 mx-auto flex flex-col">
  <h1 class="text-3xl font-bold">Create a Workout Template</h1>
  <div class="workout_start mt-7 flex flex-col">

    <%= render "templates/template_form", template: @template %>

  </div>
</div>